#!/bin/sh -e

cd src && patch -p1 < ../Makefile.in.patch
cd ..

NOCONFIGURE=1 ./autogen.sh

sed -i -e '/DATADIRNAME=/s/=.*/=share/' configure

CFLAGS="$CFLAGS -fcommon" \
CONFIG_SHELL=/bin/bash \
	./configure \
	--prefix=/usr \
	--disable-desktop-integration \
	--with-gtk3 \
	--enable-pixmaps

CFLAGS="$CFLAGS -fcommon" make
make -j1 DESTDIR="$1" install
