#!/bin/sh -e

make PREFIX=/usr \
	BUILD_STATIC_LIB=0 \
	MANDIR=/usr/share/man

make PREFIX=/usr \
	BUILD_STATIC_LIB=0 \
	MANDIR=/usr/share/man \
	DESTDIR="$1" install

install -dm755 "$1/usr/share/doc/lm-sensors"
cp -rv README INSTALL doc/* "$1/usr/share/doc/lm-sensors/"
