#!/bin/sh -e

cd nspr || exit 1

sed -ri 's#^(RELEASE_BINS=).*#\1#' pr/src/misc/Makefile.in
sed -i 's#$(LIBRARY) ##'           config/rules.mk

./configure --prefix=/usr \
	--with-mozilla \
	--with-pthreads \
	--enable-64bit

make
make DESTDIR="$1" install
