#!/bin/sh -e

mkdir -p "$1/usr/bin"
mkdir -p "$1/etc"

# Install kiss utilities.
cp -f kiss contrib/* "$1/usr/bin/"

# Install distribution documentation.
for doc in docs/site/*.txt; do
    install -Dm644 "$doc" "$1/usr/share/doc/kiss/${doc##*/}"
done

# Install the Wiki.
cp -r wiki "$1/usr/share/doc/kiss/wiki"

# Add kiss.conf
cp -f kiss.conf "$1/etc/"

# Remove unnecessary pages.
rm -f "$1/usr/share/doc/kiss/wiki/README.txt" \
      "$1/usr/share/doc/kiss/news.txt" \
      "$1/usr/share/doc/kiss/blog.txt" \
      "$1/usr/share/doc/kiss/screenshots.txt"
