#!/bin/sh -e

sed -i 's|DZEN_XMP|DZEN_XPM|g' main.c

make X11INC=/usr/include X11LIB=/usr/lib
make -C gadgets X11INC=/usr/include X11LIB=/usr/lib

make PREFIX=/usr MANPREFIX=/usr/share/man DESTDIR="$1" install
make -C gadgets PREFIX=/usr MANPREFIX=/usr/share/man DESTDIR="$1" install

install -Dm644 README* -t "$1/usr/share/doc/dzen2"
